# Generated by Django 2.0.7 on 2018-07-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(default='No title yet', max_length=100)),
                ('description_text', models.CharField(default='No description yet', max_length=400)),
                ('actors_text', models.CharField(default='No actors yet', max_length=200)),
                ('posterPath', models.CharField(default='defaultposter.jpg', max_length=256)),
                ('year', models.IntegerField(default=0)),
                ('voteCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=32)),
                ('email_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EA3.Movie')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EA3.User')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EA3.MovieCategory'),
        ),
    ]
